config/routes.rb
Vkontakte::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users

  resources :users

  resources :vkontakte_ads

  resources :vkontakte_campaigns

  resources :vkontakte_clients

end

app/models/vkontakte_client.rb
class VkontakteClient < ActiveRecord::Base
  has_many :vkontakte_campaigns
  attr_accessible :all_limit, :client_id, :day_limit, :name
end

app/controllers/vkontakte_clients_controller.rb
class VkontakteClientsController < ApplicationController
  # GET /vkontakte_clients
  # GET /vkontakte_clients.json
  def index
    @vkontakte_clients = VkontakteClient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vkontakte_clients }
    end
  end

  # GET /vkontakte_clients/1
  # GET /vkontakte_clients/1.json
  def show
    @vkontakte_client = VkontakteClient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vkontakte_client }
    end
  end

  # GET /vkontakte_clients/new
  # GET /vkontakte_clients/new.json
  def new
    @vkontakte_client = VkontakteClient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vkontakte_client }
    end
  end

  # GET /vkontakte_clients/1/edit
  def edit
    @vkontakte_client = VkontakteClient.find(params[:id])
  end

  # POST /vkontakte_clients
  # POST /vkontakte_clients.json
  def create
    @vkontakte_client = VkontakteClient.new(params[:vkontakte_client])

    respond_to do |format|
      if @vkontakte_client.save
        format.html { redirect_to @vkontakte_client, notice: 'Vkontakte client was successfully created.' }
        format.json { render json: @vkontakte_client, status: :created, location: @vkontakte_client }
      else
        format.html { render action: "new" }
        format.json { render json: @vkontakte_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vkontakte_clients/1
  # PUT /vkontakte_clients/1.json
  def update
    @vkontakte_client = VkontakteClient.find(params[:id])

    respond_to do |format|
      if @vkontakte_client.update_attributes(params[:vkontakte_client])
        format.html { redirect_to @vkontakte_client, notice: 'Vkontakte client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vkontakte_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vkontakte_clients/1
  # DELETE /vkontakte_clients/1.json
  def destroy
    @vkontakte_client = VkontakteClient.find(params[:id])
    @vkontakte_client.destroy

    respond_to do |format|
      format.html { redirect_to vkontakte_clients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vkontakte_clients_helper.rb
module VkontakteClientsHelper
end

app/views/vkontakte_clients/_form.html.erb
<%= form_for(@vkontakte_client) do |f| %>
  <% if @vkontakte_client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vkontakte_client.errors.count, "error") %> prohibited this vkontakte_client from being saved:</h2>

      <ul>
      <% @vkontakte_client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %><br />
    <%= f.number_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :day_limit %><br />
    <%= f.number_field :day_limit %>
  </div>
  <div class="field">
    <%= f.label :all_limit %><br />
    <%= f.number_field :all_limit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vkontakte_clients/edit.html.erb
<h1>Editing vkontakte_client</h1>

<%= render 'form' %>

<%= link_to 'Show', @vkontakte_client %> |
<%= link_to 'Back', vkontakte_clients_path %>

app/views/vkontakte_clients/index.html.erb
 
<h1>Клиенты</h1>

<table class="table table-striped">
  <tr>
    <th>Клиент</th>
    <th id="curr">Дневной лимит</th>
    <th id="curr">Общий лимит</th>
  </tr>

<% @vkontakte_clients.each do |vkontakte_client| %>
  <tr>
    <!--td><%= vkontakte_client.client_id %></td-->
    <td><%= link_to vkontakte_client.name, vkontakte_client %></td> 
    <td id="curr"><%= number_to_currency(vkontakte_client.day_limit) %></td>
    <td id="curr"><%= number_to_currency(vkontakte_client.all_limit) %></td>
    <!--td><%= link_to 'Show', vkontakte_client %></td>
    <td><%= link_to 'Edit', edit_vkontakte_client_path(vkontakte_client) %></td>
    <td><%= link_to 'Destroy', vkontakte_client, method: :delete, data: { confirm: 'Are you sure?' } %></td!-->
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vkontakte client', new_vkontakte_client_path, :class => 'btn btn-primary' %>

app/views/vkontakte_clients/new.html.erb
<h1>New vkontakte_client</h1>

<%= render 'form' %>

<%= link_to 'Back', vkontakte_clients_path %>

app/views/vkontakte_clients/show.html.erb
<p id="notice"><%= notice %></p>


<ul class="breadcrumb">
   <li><%= link_to 'Клиенты', vkontakte_clients_path %><span class="divider">/</span></li>
  
</ul>

<h2><%= @vkontakte_client.name %></h2> 


<div class="span11 campaign_panel">
<div id="div_main">
<div class="pull-left"> 
  <dl class="dl-horizontal">
    <dt>ID: </dt>
    <dd><%= @vkontakte_client.client_id %></dd>
    <dt>Клиент: </dt>
    <dd><%= @vkontakte_client.name %></dd>
 </dl>
</div>
<div class="pull-left">
 <dl class="dl-horizontal">
  <dt>Дневной лимит:</dt>
  <dd><%= number_to_currency @vkontakte_client.day_limit %></dd>
  <dt>Общий лимит</dt>
  <dd><%= number_to_currency @vkontakte_client.all_limit %></dd>
  </dl>
</div>
</div>
</div>

<div class="clearfix"></div>
<h4>Другие кампании <%= @vkontakte_client.name %></h4>

<table class="table table-striped">
  <tr>
    <th>Имя</th>
    <th>Клиент</th>
    <th>Status</th>
    <th id="curr">Дневной лимит</th>
    <th id="curr">Общий лимит</th>
    <th>Старт</th>
    <th>Стоп</th>
  </tr>

<% @vkontakte_client.vkontakte_campaigns.each do |vkontakte_campaign| %>
  <tr>
    <td><%= link_to vkontakte_campaign.name, vkontakte_campaign %></td>
    <td><%= link_to vkontakte_campaign.vkontakte_client.name.html_safe, @vkontakte_client %></td>
    <td><%= vkontakte_campaign.status %></td>
    <td id="curr"><%= number_to_currency vkontakte_campaign.day_limit %></td>
    <td id="curr"><%= number_to_currency vkontakte_campaign.all_limit %></td>
    <td><%= vkontakte_campaign.start_time %></td>
    <td><%= vkontakte_campaign.stop_time %></td>
  </tr>
<% end %>
</table>


<p>
  <b>Client:</b>
  <%= @vkontakte_client.client_id %>
</p>

<p>
  <b>Name:</b>
  <%= @vkontakte_client.name %>
</p>

<p>
  <b>Day limit:</b>
  <%= @vkontakte_client.day_limit %>
</p>

<p>
  <b>All limit:</b>
  <%= @vkontakte_client.all_limit %>
</p>