config/routes.rb
Vkontakte::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users

  resources :users

  resources :vkontakte_ads

  resources :vkontakte_campaigns

  resources :vkontakte_clients

end

app/models/vkontakte_ad.rb
class VkontakteAd < ActiveRecord::Base
  belongs_to :vkontakte_campaign
  attr_accessible :ad_id, :all_limit, :approved, :campaign_id, :cpc, :cpm, :disclaimer, :name, :status, :vkontakte_campaign_id
end

app/controllers/vkontakte_ads_controller.rb
class VkontakteAdsController < ApplicationController
  # GET /vkontakte_ads
  # GET /vkontakte_ads.json
  def index
    @vkontakte_ads = VkontakteAd.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vkontakte_ads }
    end
  end

  # GET /vkontakte_ads/1
  # GET /vkontakte_ads/1.json
  def show
    @vkontakte_ad = VkontakteAd.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vkontakte_ad }
    end
  end

  # GET /vkontakte_ads/new
  # GET /vkontakte_ads/new.json
  def new
    @vkontakte_ad = VkontakteAd.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vkontakte_ad }
    end
  end

  # GET /vkontakte_ads/1/edit
  def edit
    @vkontakte_ad = VkontakteAd.find(params[:id])
  end

  # POST /vkontakte_ads
  # POST /vkontakte_ads.json
  def create
    @vkontakte_ad = VkontakteAd.new(params[:vkontakte_ad])

    respond_to do |format|
      if @vkontakte_ad.save
        format.html { redirect_to @vkontakte_ad, notice: 'Vkontakte ad was successfully created.' }
        format.json { render json: @vkontakte_ad, status: :created, location: @vkontakte_ad }
      else
        format.html { render action: "new" }
        format.json { render json: @vkontakte_ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vkontakte_ads/1
  # PUT /vkontakte_ads/1.json
  def update
    @vkontakte_ad = VkontakteAd.find(params[:id])

    respond_to do |format|
      if @vkontakte_ad.update_attributes(params[:vkontakte_ad])
        format.html { redirect_to @vkontakte_ad, notice: 'Vkontakte ad was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vkontakte_ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vkontakte_ads/1
  # DELETE /vkontakte_ads/1.json
  def destroy
    @vkontakte_ad = VkontakteAd.find(params[:id])
    @vkontakte_ad.destroy

    respond_to do |format|
      format.html { redirect_to vkontakte_ads_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vkontakte_ads_helper.rb
module VkontakteAdsHelper
end

app/views/vkontakte_ads/_form.html.erb
<%= form_for(@vkontakte_ad) do |f| %>
  <% if @vkontakte_ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vkontakte_ad.errors.count, "error") %> prohibited this vkontakte_ad from being saved:</h2>

      <ul>
      <% @vkontakte_ad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ad_id %><br />
    <%= f.number_field :ad_id %>
  </div>
  <div class="field">
    <%= f.label :campaign_id %><br />
    <%= f.number_field :campaign_id %>
  </div>
  <div class="field">
    <%= f.label :vkontakte_campaign %><br />
    <%= f.text_field :vkontakte_campaign %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :approved %><br />
    <%= f.number_field :approved %>
  </div>
  <div class="field">
    <%= f.label :all_limit %><br />
    <%= f.text_field :all_limit %>
  </div>
  <div class="field">
    <%= f.label :cpc %><br />
    <%= f.number_field :cpc %>
  </div>
  <div class="field">
    <%= f.label :cpm %><br />
    <%= f.number_field :cpm %>
  </div>
  <div class="field">
    <%= f.label :disclaimer %><br />
    <%= f.check_box :disclaimer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vkontakte_ads/edit.html.erb
<h1>Editing vkontakte_ad</h1>

<%= render 'form' %>

<%= link_to 'Show', @vkontakte_ad %> |
<%= link_to 'Back', vkontakte_ads_path %>

app/views/vkontakte_ads/index.html.erb
<h1>Объявления</h1>

<table class="table table-striped">
  <tr>
    <th>Имя</th>
    <th>Кампания</th>
    <th>Клиент</th>
    <th>Статус</th>
    <th>Одобрено</th>
    <th>Лимит</th>
    <th>Cpc</th>
    <th>Cpm</th>
    <th>Disclaimer</th>
  </tr>

<% @vkontakte_ads.each do |vkontakte_ad| %>
  <tr>
   
    <td><%= link_to vkontakte_ad.name.html_safe, vkontakte_ad %></td>
    <td><%= link_to vkontakte_ad.vkontakte_campaign.name.html_safe, vkontakte_ad.vkontakte_campaign %></td>
    <td><%= link_to vkontakte_ad.vkontakte_campaign.vkontakte_client.name, vkontakte_ad.vkontakte_campaign.vkontakte_client %></td>
    <td><%= vkontakte_ad.status %></td>
    <td><%= vkontakte_ad.approved %></td>
    <td id="curr"><%= number_to_currency(vkontakte_ad.all_limit) %></td>
    <td><%= vkontakte_ad.cpc %></td>
    <td><%= vkontakte_ad.cpm %></td>
    <td><%= vkontakte_ad.disclaimer %></td>
  </tr>
<% end %>
</table>

<br />

app/views/vkontakte_ads/new.html.erb
<h1>New vkontakte_ad</h1>

<%= render 'form' %>

<%= link_to 'Back', vkontakte_ads_path %>

app/views/vkontakte_ads/show.html.erb
<p id="notice"><%= notice %></p>
<ul class="breadcrumb">
   <li><%= link_to 'Клиенты', vkontakte_clients_path %><span class="divider">/</span></li>
   <li><%= link_to 'Кампании', vkontakte_campaigns_path %><span class="divider">/</span></li>
  
</ul>
<h2>
  
  <%= @vkontakte_ad.name %>
</h2>

<p>
  <b>Campaign:</b>
  <%= @vkontakte_ad.campaign_id %>
</p>

<p>
  <b>Vkontakte campaign:</b>
  <%= @vkontakte_ad.vkontakte_campaign %>
</p>

<p>
  <b>Name:</b>
  <%= @vkontakte_ad.name %>
</p>

<p>
  <b>Status:</b>
  <%= @vkontakte_ad.status %>
</p>

<p>
  <b>Approved:</b>
  <%= @vkontakte_ad.approved %>
</p>

<p>
  <b>All limit:</b>
  <%= @vkontakte_ad.all_limit %>
</p>

<p>
  <b>Cpc:</b>
  <%= @vkontakte_ad.cpc %>
</p>

<p>
  <b>Cpm:</b>
  <%= @vkontakte_ad.cpm %>
</p>

<p>
  <b>Disclaimer:</b>
  <%= @vkontakte_ad.disclaimer %>
</p>