config/routes.rb
Vkontakte::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users

  resources :users

  resources :vkontakte_ads

  resources :vkontakte_campaigns

  resources :vkontakte_clients

end

app/models/vkontakte_campaign.rb
class VkontakteCampaign < ActiveRecord::Base
  belongs_to :vkontakte_client
  has_many :vkontakte_ads
  attr_accessible :account_id, :all_limit, :campaign_id, :client_id, :day_limit, :name, :start_time, :status, :stop_time, :vkontakte_client_id
end

app/controllers/vkontakte_campaigns_controller.rb
class VkontakteCampaignsController < ApplicationController
  # GET /vkontakte_campaigns
  # GET /vkontakte_campaigns.json
  def index
    @vkontakte_campaigns = VkontakteCampaign.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vkontakte_campaigns }
    end
  end

  # GET /vkontakte_campaigns/1
  # GET /vkontakte_campaigns/1.json
  def show
    @vkontakte_campaign = VkontakteCampaign.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vkontakte_campaign }
    end
  end

  # GET /vkontakte_campaigns/new
  # GET /vkontakte_campaigns/new.json
  def new
    @vkontakte_campaign = VkontakteCampaign.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vkontakte_campaign }
    end
  end

  # GET /vkontakte_campaigns/1/edit
  def edit
    @vkontakte_campaign = VkontakteCampaign.find(params[:id])
  end

  # POST /vkontakte_campaigns
  # POST /vkontakte_campaigns.json
  def create
    @vkontakte_campaign = VkontakteCampaign.new(params[:vkontakte_campaign])

    respond_to do |format|
      if @vkontakte_campaign.save
        format.html { redirect_to @vkontakte_campaign, notice: 'Vkontakte campaign was successfully created.' }
        format.json { render json: @vkontakte_campaign, status: :created, location: @vkontakte_campaign }
      else
        format.html { render action: "new" }
        format.json { render json: @vkontakte_campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vkontakte_campaigns/1
  # PUT /vkontakte_campaigns/1.json
  def update
    @vkontakte_campaign = VkontakteCampaign.find(params[:id])

    respond_to do |format|
      if @vkontakte_campaign.update_attributes(params[:vkontakte_campaign])
        format.html { redirect_to @vkontakte_campaign, notice: 'Vkontakte campaign was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vkontakte_campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vkontakte_campaigns/1
  # DELETE /vkontakte_campaigns/1.json
  def destroy
    @vkontakte_campaign = VkontakteCampaign.find(params[:id])
    @vkontakte_campaign.destroy

    respond_to do |format|
      format.html { redirect_to vkontakte_campaigns_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vkontakte_campaigns_helper.rb
module VkontakteCampaignsHelper
end

app/views/vkontakte_campaigns/_form.html.erb
<%= form_for(@vkontakte_campaign) do |f| %>
  <% if @vkontakte_campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vkontakte_campaign.errors.count, "error") %> prohibited this vkontakte_campaign from being saved:</h2>

      <ul>
      <% @vkontakte_campaign.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br />
    <%= f.number_field :account_id %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br />
    <%= f.number_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :campaign_id %><br />
    <%= f.number_field :campaign_id %>
  </div>
  <div class="field">
    <%= f.label :vkontakte_client %><br />
    <%= f.text_field :vkontakte_client %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :day_limit %><br />
    <%= f.text_field :day_limit %>
  </div>
  <div class="field">
    <%= f.label :all_limit %><br />
    <%= f.text_field :all_limit %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :stop_time %><br />
    <%= f.datetime_select :stop_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vkontakte_campaigns/edit.html.erb
<h1>Editing vkontakte_campaign</h1>

<%= render 'form' %>

<%= link_to 'Show', @vkontakte_campaign %> |
<%= link_to 'Back', vkontakte_campaigns_path %>

app/views/vkontakte_campaigns/index.html.erb
<h1>Кампании</h1>

<table class="table table-striped">
  <tr>
    <th>Имя</th>
    <th>Клиент</th>
    <th>Status</th>
    <th id="curr">Дневной лимит</th>
    <th id="curr">Общий лимит</th>
    <th>Старт</th>
    <th>Стоп</th>
  </tr>

<% @vkontakte_campaigns.each do |vkontakte_campaign| %>
  <tr>
    <td><%= link_to vkontakte_campaign.name, vkontakte_campaign %></td>
    <td><%= link_to vkontakte_campaign.vkontakte_client.name.html_safe, vkontakte_campaign.vkontakte_client %></td>
    <td><%= vkontakte_campaign.status %></td>
    <td id="curr"><%= number_to_currency vkontakte_campaign.day_limit %></td>
    <td id="curr"><%= number_to_currency vkontakte_campaign.all_limit %></td>
    <td><%= vkontakte_campaign.start_time %></td>
    <td><%= vkontakte_campaign.stop_time %></td>
  </tr>
<% end %>
</table>

<br />

app/views/vkontakte_campaigns/new.html.erb
<h1>New vkontakte_campaign</h1>

<%= render 'form' %>

<%= link_to 'Back', vkontakte_campaigns_path %>

app/views/vkontakte_campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<ul class="breadcrumb">
   <li><%= link_to 'Клиенты', vkontakte_clients_path %><span class="divider">/</span></li>
  
</ul>

<h2>Кампания: <%= @vkontakte_campaign.name %></h2> 


<div class="span11 campaign_panel">
<div id="div_main">
<div class="pull-left"> 
  <dl class="dl-horizontal">
    <dt>Аккаунт: </dt>
    <dd><%= @vkontakte_campaign.account_id %></dd>
    <dt>Кампания: </dt>
    <dd><%= @vkontakte_campaign.campaign_id %></dd>
    <dt>Статус: </dt>
    <dd><%= @vkontakte_campaign.status %></dd>
    <dt>ID клиента: </dt>
    <dd><%= @vkontakte_campaign.client_id %></dd>
 </dl>
</div>
<div class="pull-left">
 <dl class="dl-horizontal">
  <dt>Дневной лимит:</dt>
  <dd><%= number_to_currency @vkontakte_campaign.day_limit %></dd>
  <dt>Общий лимит</dt>
  <dd><%= number_to_currency @vkontakte_campaign.all_limit %></dd>
  <dt>Старт</dt>
  <dd><%= @vkontakte_campaign.start_time %></dd>
  <dt>Стоп</dt>
  <dd><%= @vkontakte_campaign.stop_time %></dd>
  </dl>
</div>
</div>
</div>

<div class="clearfix"></div>
<h3>Другие объявления <%= @vkontakte_campaign.name %></h3>

<table class="table table-striped">
  <tr>
    <th>Имя</th>
    <th>Кампания</th>
    <th>Клиент</th>
    <th>Статус</th>
    <th>Одобрено</th>
    <th>Лимит</th>
    <th>Cpc</th>
    <th>Cpm</th>
    <th>Disclaimer</th>
  </tr>

<% @vkontakte_campaign.vkontakte_ads.each do |vkontakte_ad| %>
  <tr>
   
    <td><%= link_to vkontakte_ad.name.html_safe, vkontakte_ad %></td>
    <td><%= link_to vkontakte_ad.vkontakte_campaign.name.html_safe, vkontakte_ad.vkontakte_campaign %></td>
    <td><%= link_to vkontakte_ad.vkontakte_campaign.vkontakte_client.name, vkontakte_ad.vkontakte_campaign.vkontakte_client %></td>
    <td><%= vkontakte_ad.status %></td>
    <td><%= vkontakte_ad.approved %></td>
    <td id="curr"><%= number_to_currency vkontakte_ad.all_limit %></td>
    <td><%= vkontakte_ad.cpc %></td>
    <td><%= vkontakte_ad.cpm %></td>
    <td><%= vkontakte_ad.disclaimer %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Edit', edit_vkontakte_campaign_path(@vkontakte_campaign) %> |
<%= link_to 'Back', vkontakte_campaigns_path %>